---
- name: Ensure SELinux policy is enforced
  hosts: all
  tasks:
    - name: Install SELinux Python library
      ansible.builtin.pip:
        name: libselinux-python
        state: present
    - name: Ensure SELinux policy is currently enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing
      become: true
